language: java
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
services:
  - mongodb
script:
- mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR
